### ISSUE TITLE
Error when ordering a List of targets in Postgresql.

### ISSUE THREAD

**Issue by glaubervila** [linea-it/dri#1283]
The error happens when trying to sort the list by any column. 
the message below appears in the log. 

the error is probably caused by the way Postgresql handles columns of the same name in the case of id. that exists in the table referring to the rating and reject list. when he tries to order he complains that he should be on the group by list.
Possible solution, instead of using Select * for postgresql to explicitly use the list of columns you want in the query. Note: This error does not happen in Oracle.

How to reproduce:

- Open the target viewer
- Select an existing list or add a new one.
- The list must have at least one property that is not (Id, RA, Dec)
- After loading the list of objects, click on one of the properties to sort.
- Loading takes a while and an error message is returned. "Sorry there was an error, and it was not possible to list the objects."

Log:
```
2020-12-14 19:41:38,707 [INFO] Target Query: [ SELECT a.meta_id, a.coadd_object_id, a.ra, a.dec, a.mag_auto_g, a.boo, b.id AS meta_rating_id, b.rating AS meta_rating, c.id AS meta_reject_id, c.reject AS meta_reject  FROM dri_catalog.lista_300_objetos AS a LEFT OUTER JOIN dri_catalog.catalog_rating AS b ON b.catalog_id = 25 AND b.owner = 1 AND CAST(a.meta_id AS VARCHAR) = b.object_id LEFT OUTER JOIN dri_catalog.catalog_reject AS c ON c.catalog_id = 25 AND c.owner = 1 AND (CAST(a.meta_id AS VARCHAR) = c.object_id OR c.id IS NULL) ORDER BY a.meta_id   LIMIT 100 OFFSET 0 ]
2020-12-14 19:41:38,769 [ERROR] Internal Server Error: /dri/api/target/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.GroupingError: column "a.meta_id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 2: ...S VARCHAR) = c.object_id OR c.id IS NULL) ORDER BY a.meta_id
                                                              ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/catalog/views.py", line 109, in list
    url_filters=request.query_params
  File "/app/lib/CatalogDB.py", line 150, in query
    count = self.stm_count(stm)
  File "/app/lib/sqlalchemy_wrapper.py", line 258, in stm_count
    queryset = con.execute(stm_count)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.GroupingError) column "a.meta_id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 2: ...S VARCHAR) = c.object_id OR c.id IS NULL) ORDER BY a.meta_id
                                                              ^
```

**Comment by glaubervila** [comment]
Closed in v2.3  Fixed in #1281
