### ISSUE TITLE
Error in serialization for model footprint

### ISSUE THREAD

**Issue by alanot** [linea-it/dri#24]
AttributeError at /footprints/

'NoneType' object has no attribute 'serializer'

**Comment by glaubervila** [comment]
alisson vc está com dados no seu banco de dados? esse model esta funcionando corretamente para mim

**Comment by alanot** [comment]
estou com os dados do fixtures/filters.json

**Comment by glaubervila** [comment]
tem este repositorio https://github.com/linea-it/dri-coadd_data faz um clone dele e faz o loaddata de cada um deles a ordem é release, tag, tiles, dataset, survey e os outros nao tem problema a ordem

**Comment by alanot** [comment]
(env) alanot@tet-05919:/home/des-dri/api$ python manage.py loaddata ../data/dataset.json 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/des-dri/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/des-dri/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/des-dri/env/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/des-dri/env/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/des-dri/env/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/home/des-dri/env/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 106, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/home/des-dri/env/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 292, in check_constraints
    referenced_table_name, referenced_column_name))
django.db.utils.IntegrityError: Problem installing fixtures: The row in table 'coadd_dataset' with primary key '3411' has an invalid foreign key: coadd_dataset.tag_id contains a value '40' that does not have a corresponding value in coadd_tag.id.

**Comment by glaubervila** [comment]
se vc não tiver nada de importante no teu banco faz o seguinte:
python manage.py flush ( apaga o banco de dados )
python manage.py loaddata release.json
python manage.py loaddata tag.json
python manage.py loaddata tiles.json
python manage.py loaddata dataset.json
python manage.py loaddata survey.json
e se tiver mais json faz os outros.

**Comment by alanot** [comment]
esquece, ja descobri que o dataset.py precisa ser executado depois...

**Comment by alanot** [comment]
O erro persiste

**Comment by glaubervila** [comment]
o meu está funcionando chama no skype
