### ISSUE TITLE
Save As error ORA-00918: column ambiguously defined

### ISSUE THREAD

**Issue by glaubervila** [linea-it/dri#745]
Esse ocorreu com ogando tentando aplicar um filtro e fazer um save as.
fiz um filtro de richness >= 70 com o cluster 12

`
{"exc_message": "(cx_Oracle.DatabaseError) ORA-00918: column ambiguously defined\n [SQL: \"CREATE TABLE brportal.rich70_12 AS SELECT seqnr, ra_init, dec_init, radius_saddle_mpc, radius_iso_mpc, radius_iso_mpc_init, radius_iso_amin, radius_snr, z_init, zmin_cyl, zmax_cyl, contrast_cyl, nmax_cyl, maxpix, ngals_rmin_init, ngals_core_init, snr_init, contrast_init, local_bkg_iz_r, mean_bkg_iz_r, area_local_bkg, masked_frac_r2, masked_frac_r1, masked_frac_r05, eff_frac_r05, target_distance, detection_tile, id_in_tile, iz_init, peak_id, xpeak, ypeak, xpeak_hr, ypeak_hr, npeaks_dom, domain_id, org_domain_id, cyl_nsl, flag_neighbour, ra, dec, sigma_dz_init, sigma_dz, ngals, ngals_err, ngals_rmin, ngals_rcc, sigma_bkg, radius_half_n_mpc, radius_half_n_amin, radius_cc_mpc, radius_cc_amin, radius_max_mpc, radius_max_amin, contrast_rhalf, contrast_rmax, contrast_rcc, snr, contrast, concentration, concentration_cen, zp, z_err, nmem, flag_radius_cut, flag_deblend, local_bkg_r, mean_bkg_r, ra_bcg, dec_bcg, dcen_bcg, mag_bcg, zp_bcg, zs, rank, id, tilename \\nFROM brportal.e_1488_2721 a LEFT OUTER JOIN driportal.catalog_rating b ON a.id = b.object_id LEFT OUTER JOIN driportal.catalog_reject c ON a.id = c.object_id OR c.id IS NULL \\nWHERE a.ngals >= '70'\"]", "exc_type": "DatabaseError"}
`
Traceback retirado do Cellery

`
Traceback (most recent call last):
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-00918: column ambiguously defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/celery/app/trace.py", line 623, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/celery/app/task.py", line 379, in __call__
    return self.run(*args, **kwargs)
  File "/srv/domain/desportal.cosmology.illinois.edu/api/product/tasks.py", line 468, in product_save_as
    saveas.create_table_by_product_id(user_id, product_id, name, filter_id, description)
  File "/srv/domain/desportal.cosmology.illinois.edu/api/product/saveas.py", line 83, in create_table_by_product_id
    stm=stm
  File "/srv/domain/desportal.cosmology.illinois.edu/api/product/saveas.py", line 112, in create_table_as
    catalog.create_table_as(table=table, stm=stm, schema=schema)
  File "/srv/domain/desportal.cosmology.illinois.edu/api/lib/sqlalchemy_wrapper.py", line 247, in create_table_as
    return con.execute(create_stm)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00918: column ambiguously defined
 [SQL: "CREATE TABLE brportal.rich70_12 AS SELECT seqnr, ra_init, dec_init, radius_saddle_mpc, radius_iso_mpc, radius_iso_mpc_init, radius_iso_amin, radius_snr, z_init, zmin_cyl, zmax_cyl, contrast_cyl, nmax_cyl, maxpix, ngals_rmin_init, ngals_core_init, snr_init, contrast_init, local_bkg_iz_r, mean_bkg_iz_r, area_local_bkg, masked_frac_r2, masked_frac_r1, masked_frac_r05, eff_frac_r05, target_distance, detection_tile, id_in_tile, iz_init, peak_id, xpeak, ypeak, xpeak_hr, ypeak_hr, npeaks_dom, domain_id, org_domain_id, cyl_nsl, flag_neighbour, ra, dec, sigma_dz_init, sigma_dz, ngals, ngals_err, ngals_rmin, ngals_rcc, sigma_bkg, radius_half_n_mpc, radius_half_n_amin, radius_cc_mpc, radius_cc_amin, radius_max_mpc, radius_max_amin, contrast_rhalf, contrast_rmax, contrast_rcc, snr, contrast, concentration, concentration_cen, zp, z_err, nmem, flag_radius_cut, flag_deblend, local_bkg_r, mean_bkg_r, ra_bcg, dec_bcg, dcen_bcg, mag_bcg, zp_bcg, zs, rank, id, tilename \nFROM brportal.e_1488_2721 a LEFT OUTER JOIN driportal.catalog_rating b ON a.id = b.object_id LEFT OUTER JOIN driportal.catalog_reject c ON a.id = c.object_id OR c.id IS NULL \nWHERE a.ngals >= '70'"]
`

**Comment by glaubervila** [comment]
Corrigido no Pull Request #887 #886
